### ISSUE TITLE
Architect error

### ISSUE THREAD

**Issue by taulal** [tjeerdintveen/Vurig-Calendar#6]
Hi TJ,

Great calendar! it works so cleanly, love it,

Hey Im just having a small error when trying to place it in a project (target 5.0),

Getting this error,
ld: symbol(s) not found for architecture i386

Is there any framework or dependencies I should be linking to the project to make it work? 

Kind regards
Taulal

**Comment by tjeerdintveen** [comment]
Glad you like it!
Did you add the Quartz framework?

**Comment by taulal** [comment]
Ahh right that seemed to fix it thank you! 

Hey one other quick question. When my app goes landscape I need to change the position and size of the calendar. What would be the best way to do that? 

Thanks for your time.

**Comment by tjeerdintveen** [comment]
Well I would not use a tiled-based calendar like this one. If you look at the original calendar, you'll see a different kind of view in landscape mode.

But if you must, then I would suggest you dive a little bit into quartz drawing (it's not too difficult really), and find and alter the sizes of the squares. Everything is commented so that should give you a headstart!

**Comment by taulal** [comment]
The calendar I am creating does not require for the size to be changed in landscape and portrait mode, simply the position whole CalendarView, but yes I may have to dive into quartz drawing.

Hey one other quick question, When I select a date the date being show in the nslog as the currentDate is being offset by a day. I believe this is because it is not reading my nsTimeZone, is there a way I can put this into the code somewhere?  

I have been looking around to find a place to add in the timeZone but can seem to find the right place.

Thanks for all your help,
T
