### ISSUE TITLE
select date ?

### ISSUE THREAD

**Issue by xxdd** [tjeerdintveen/Vurig-Calendar#7]
Great project!  I like it 

I select 2012-12-15 ,but output      Selected date = 2012-12-14 16:00:00 +0000, why?
can you help me?

**Comment by bayfatih2000** [comment]
I have same problem. Please help.

**Comment by tjeerdintveen** [comment]
Must be because of the date time selector in the NSDate category. I have no time to fix it but I'm sure you can find the answer there.

**Comment by markelsoft** [comment]
Does your component have an open source license?   I am using your VRGCalendarView component with another component I am developing and would like to distribute your calendar view with my component.   Since it is on Github is there an Open Source license?  The header files have a copyright?   Thank you and nice component.

**Comment by tjeerdintveen** [comment]
It's MIT license. Go ahead.

**Comment by markelsoft** [comment]
thank you.

**Comment by esunly88** [comment]
Can you please give a fix to this issue? I cannot fix it. Thanks in advances

**Comment by edward-lay** [comment]
Could anyone solve this issue or found a workaround?

I have placed the following code
[formatter setTimeZone:[NSTimeZone timeZoneWithAbbreviation:@"GMT"]];
but still got a previous date.
